#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Function to modify mesh size
modifyMeshSize() {

  meshSize=$1

  # Check user input
  if [ "$meshSize" != "fine" ] && [ "$meshSize" != "medium" ] && [ "$meshSize" != "coarse" ]; then
    echo "Invalid mesh size. Please choose from fine, medium, or coarse."
    exit 1
  fi

  # Modify system/blockMeshDict file
  file="./system/blockMeshDict"

  # Set new mesh values based on user input
  case $meshSize in
    fine)
      newMeshValues1="100 424 1"  
      newMeshValues2="600 424 1"  
      ;;
    medium)
      newMeshValues1="75 300 1"  
      newMeshValues2="450 300 1"   
      ;;
    coarse)
      newMeshValues1="53 212 1"  
      newMeshValues2="318 212 1"  
      ;;
  esac
  # Line to mofify in blockMeshDict
  firstLine=43
  secondLine=44

  # Replace the values in the specified lines
  sed -i "${firstLine}s/\((\s*[0-9]\+\s*[0-9]\+\s*1\s*)\)/($newMeshValues1)/" $file
  sed -i "${secondLine}s/\((\s*[0-9]\+\s*[0-9]\+\s*1\s*)\)/($newMeshValues2)/" $file

  echo "Mesh size has been updated to $meshSize."
}

# Clean old log files
rm -f log*.*

# Ask user to choose mesh size
if [ -n "$1" ]; then
  meshSize=$1
else
  read -p "What mesh size do you want? (fine, medium, coarse): " meshSize
fi

modifyMeshSize $meshSize


# Prepare mesh
foamCleanPolyMesh
runApplication blockMesh

# Decompose mesh
runApplication decomposePar -force

# Run solver 
runParallel simpleFoam

# Reconstruct data
runApplication reconstructPar
rm -rf processor*

# Generate plots with matplotlib
python3 ../create_figures.py

