#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Function to modify mesh size
modifyMeshSize() {
  # Prompt user for mesh size
  read -p "What mesh size do you want? (fine, intermediate, coarse): " meshSize

  # Check user input
  if [ "$meshSize" != "fine" ] && [ "$meshSize" != "intermediate" ] && [ "$meshSize" != "coarse" ]; then
    echo "Invalid mesh size. Please choose from fine, intermediate, or coarse."
    return 1
  fi

  # Modify system/blockMeshDict file
  file="./system/blockMeshDict"

  # Set new mesh values based on user input
  case $meshSize in
    fine)
      newMeshValues1="100 424 1"  
      newMeshValues2="600 424 1"  
      ;;
    intermediate)
      newMeshValues1="75 300 1"  
      newMeshValues2="450 300 1"   
      ;;
    coarse)
      newMeshValues1="53 212 1"  
      newMeshValues2="318 212 1"  
      ;;
  esac
  # Line to mofify in blockMeshDict
  firstLine=37
  secondLine=38

  # Replace the values in the specified lines
  sed -i "${firstLine}s/\((\s*[0-9]\+\s*[0-9]\+\s*1\s*)\)/($newMeshValues1)/" $file
  sed -i "${secondLine}s/\((\s*[0-9]\+\s*[0-9]\+\s*1\s*)\)/($newMeshValues2)/" $file

  echo "Mesh size has been updated to $meshSize."
}

# Clean old log files
rm -f log*.*

# Ask user to choose mesh size
modifyMeshSize

# Prepare mesh
foamCleanPolyMesh
runApplication blockMesh

# Run solver 
runApplication simpleFoam

# Generate plots with gnuplot
runApplication gnuplot cf.gpl
