#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean
wclean turbulenceModels
wclean incompressible
wclean compressible

# ----------------------------------------------------------------- end-of-file
