#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wmake libso turbulenceModels
wmake libso incompressible
wmake libso compressible

# ----------------------------------------------------------------- end-of-file
