#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean turbulenceModels
wclean libso incompressible
# wclean compressible

# ----------------------------------------------------------------- end-of-file
