---
title: "myTurbulenceModels"
author: "Jiří Fürst"
---

This package provides turbulence models for use in OpenFOAM simulations. It includes implementations of various RANS and LES models, along with utilities for model selection and parameter tuning.

## Installation

You can install the package from GitHub using the following command:
```bash
git clone https://github.com/furstj/myTurbulenceModels.git
cd myTurbulenceModels
./Allwmake
```

## Features

### RANS Models
The package contains following RANS turbulence models:

- [`kOmegaTNT`](RANS/kOmegaTNT.qmd) - Two-Equation k-ω Turbulence Model due to J. C. Kok
- [`kOmegaWilcox06`](RANS/kOmegaWilcox06.qmd) - Two-Equation k-ω Turbulence Model due to Wilcox
- [`EARSM`](RANS/EARSM.qmd)  - Explicit Algebraic Reynolds Stress Model due to Hellsten
- [`EARSMWallin`](RANS/EARSMWallin.qmd) - EARSM with Wallin's Modifications
- [`kOmegaSSTCC`](RANS/kOmegaSSTCC.qmd) - Shear Stress Transport k-ω Model with Curvature Correction
- [`kOmegaSSTCCM`](RANS/kOmegaSSTCCM.qmd) - Shear Stress Transport k-ω Model with Curvature Correction

It also includes the following transitional RANS turbulence models:

- [`kOmegaSSTLMRough`](Transition/kOmegaSSTLMRough.qmd) - Five-equation Transition and Turbulence Model with Roughness Modifications
- [`gammaSST`](Transition/gammaSST.qmd) - Three-equation transition and turbulence Model
- [`mykkLOmega`](Transition/mykkLOmega.qmd) - Three-equation transition and turbulence Model due to Walters and Cokljat
- [`kv2Omega`](Transition/kv2Omega.qmd) - Three-equation transition and turbulence Model due to Walters and ???
- [`kOmegaTrans`](Transition/kOmegaTrans.qmd) - Two-equation transition and turbulence (experimental)
- [`EARSMTrans`](Transition/EARSMTrans.qmd) - Explicit Algebraic Reynolds Stress Model with Transition (experimental)

### LES Models
The package also provides the following LES turbulence models:

- [`XLES`](LES/XLES.qmd) - Extra Large Eddy Simulation Model due to J. C. Kok

### Boundary conditions
The package includes specialized boundary conditions for turbulence quantities, such as:

- [`omegaViscosityRatio`](BoCos/omegaViscosityRatio.qmd) - Inlet boundary condition for ω based on $\nu^t/\nu$ viscosity ratio
- [`boundedTurbulentIntensityKineticEnergyInlet`](BoCos/boundedTurbulentIntensityKineticEnergyInlet.qmd) -Inlet boundary condition for k based on turbulent intensity with lower and upper bounds
- [`ReThetatInlet`](BoCos/ReThetatInlet.qmd) - Inlet boundary condition for $Re_{\theta,t}$ for Langtry and Menter transitional model
- [`roughnessAmplification`](BoCos/roughnessAmplification.qmd) - Wall boundary condition for $A_r$ for roughness modifications in transitional models
- [`roughnessAmplificationLangel`](BoCos/roughnessAmplificationLangel.qmd) - Wall boundary condition for $A_r$ for roughness modifications in transitional models by Langel
- [`nutUKnoppWallFunction`](BoCos/nutUKnoppWallFunction.qmd) - Wall function for turbulent viscosity based on Knopp et al.
- [`omegaRoughWallFunction`](BoCos/omegaRoughWallFunction.qmd) - Wall function for ω considering surface roughness
- [`omegaWilcoxRoughWallFunction`](BoCos/omegaWilcoxRoughWallFunction.qmd) - Wall function for ω considering surface roughness due to Wilcox
