#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Ask user to choose mesh size
if [ -n "$1" ]; then
  meshSize=$1
else
  read -p "What mesh size do you want? (fine, medium, coarse): " meshSize
fi



# Prepare mesh
foamCleanPolyMesh
runApplication blockMesh -dict system/blockMeshDict.$meshSize

# Decompose mesh
runApplication decomposePar -force

# Run solver 
runParallel simpleFoam

# Reconstruct data
runApplication reconstructPar
rm -rf processor*

# Generate plots with matplotlib
python3 ../create_figures.py

