#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -f log*.*

# Preparing Mesh
foamCleanPolyMesh
runApplication blockMesh

# Running in serial
runApplication simpleFoam 

runApplication wallShearStress -latestTime
runApplication sample -latestTime

runApplication gnuplot cf.gpl

