#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh

runApplication renumberMesh -overwrite

restore0Dir

runApplication simpleFoam

gnuplot plot_cf.gpi
