#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -f log*.*

# Preparing Mesh
foamCleanPolyMesh
runApplication blockMesh

# Running in parallel
runApplication decomposePar

runParallel simpleFoam 

runApplication reconstructPar

rm -rf processor*

runApplication gnuplot cf.gpl

