---
title: "kOmegaTNT model"
---
The `kOmegaTNT` model is a simple two-equation RANS turbulence model developed by J. C. Kok [@Kok2000]. It is a modification of the original Wilcox k-ω model [@Wilcox1994], designed to remove strong dependency on the free-stream value of ω. This is achieved by including a cross-diffusion term in the ω equation, similar to the SST model by Menter [@Menter1994], and by re-calibration of model coefficients.

## Model Equations
The transport equations for the `kOmegaTNT` model are given by:

$$
\begin{aligned}
\frac{\partial (\rho k)}{\partial t} + \frac{\partial (\rho k u_j)}{\partial x_j} &= P_k - \beta^* \rho k \omega + \frac{\partial}{\partial x_j} \left[ (\mu + \sigma_k \mu_t) \frac{\partial k}{\partial x_j} \right], 
\\
\frac{\partial (\rho \omega)}{\partial t} + \frac{\partial (\rho \omega u_j)}{\partial x_j} &= P_\omega - \beta \rho \omega^2 + \frac{\partial}{\partial x_j} \left[ (\mu + \sigma_\omega \mu_t) \frac{\partial \omega}{\partial x_j} \right] + C_D,
\end{aligned}
$$
where:
$$
\begin{aligned}
P_k &= \tau_{ij} \frac{\partial u_i}{\partial x_j}, \\
P_\omega &= \frac{\alpha_\omega \omega}{k} P_k, \\
C_D &= \frac{\sigma_d \rho}{\omega} \max\left[\frac{\partial k}{\partial x_j} \frac{\partial \omega}{\partial x_j}, 0\right].
\end{aligned}
$$

Turbulent viscosity is computed as:
$$
\mu_t = \rho \frac{k}{\omega}.
$$

## Model Coefficients
The model coefficients are set to the following values:

- $\beta^* = 0.09$
- $\beta = 0.075$
- $\sigma_k = \frac{2}{3}$
- $\sigma_\omega = 0.5$
- $\alpha_\omega = 5/9$
- $\sigma_d = 0.5$

## Modifications

There are two optional modifications available for the `kOmegaTNT` model:

- **production limiter**: Limits the production term $P_k$ to prevent excessive turbulence generation in adverse pressure gradient flows. The limiter is applied to the equation for $k$ where it replaces $P_k$ with:
  $$
  \tilde{P}_k = \min\left(P_k, 20 \beta^* \rho k \omega\right).
  $$
  
- **shock limiter**: Reduces the turbulent viscosity in the presence of shocks to avoid nonphysical results. The limiter is applied to the equation for $k$ where it replaces $P_k$ with:
  $$
  \tilde{P}_k = \min\left(P_k, k \sqrt{S_{ij} S_{ij}}\right).
  $$
 
The source term in the $\omega$ equation is left unmodified.


## Notes on OpenFOAM implementation

OpenFOAM implementation uses slightly different notation for some coefficients:

- `Cmu` is used for $\beta^*$ 
- `beta` is used for $\beta$
- `gamma` is used for $\alpha_\omega$
- `alphaK` is used for $\sigma_k$
- `alphaOmega` is used for $\sigma_\omega$
- `alphaD` is used for $\sigma_d$

Moreover, OpenFOAM works with kinematic turbulent viscosity `nut` multiplied by density instead of turbulent viscosity `mu_t`. 